artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/shadow-1310/data/raw/main/goodreads10k.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  unzip_data_dir:
    books: artifacts/data_ingestion/books.csv
    ratings: artifacts/data_ingestion/ratings.csv
    genre: artifacts/data_ingestion/book_tags.csv
    genre_meta: artifacts/data_ingestion/tags.csv



# data_transformation:
#   root_dir: artifacts/data_transformation
#   data_path: artifacts/data_ingestion/goodreads10k.csv



# model_trainer:
#   root_dir: artifacts/model_trainer
#   train_data_path: artifacts/data_transformation/train.csv
#   test_data_path: artifacts/data_transformation/test.csv
#   model_name: model.joblib



# model_evaluation:
#   root_dir: artifacts/model_evaluation
#   test_data_path: artifacts/data_transformation/test.csv
#   model_path: artifacts/model_trainer/model.joblib
#   metric_file_name: artifacts/model_evaluation/metrics.json






