artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/shadow-1310/data/raw/main/goodreads10k.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  unzip_data_dir:
    books: artifacts/data_ingestion/books.csv
    ratings: artifacts/data_ingestion/ratings.csv
    genre: artifacts/data_ingestion/book_tags.csv
    genre_meta: artifacts/data_ingestion/tags.csv



data_transformation:
  root_dir: artifacts/data_transformation
  unzip_data_dir:
    books: artifacts/data_ingestion/books.csv
    ratings: artifacts/data_ingestion/ratings.csv
    genre: artifacts/data_ingestion/book_tags.csv
    genre_meta: artifacts/data_ingestion/tags.csv
  transformed_data_dir:
    books: artifacts/data_transformation/clean_books.csv
    ratings: artifacts/data_transformation/clean_ratings.csv
    genre: artifacts/data_transformation/clean_genre.csv
    genre_meta: artifacts/data_transformation/clean_genre_meta.csv
    trusted_user: artifacts/data_transformation/trusted_user.csv
    




model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: 
    books: artifacts/data_transformation/clean_books.csv
    ratings: artifacts/data_transformation/clean_ratings.csv
    genre: artifacts/data_transformation/clean_genre.csv
    genre_meta: artifacts/data_transformation/clean_genre_meta.csv
    trusted_user: artifacts/data_transformation/trusted_user.csv
  model_path: 
    simple:
      root_dir: artifacts/model_trainer/simple_recommender
      top_books: artifacts/model_trainer/simple_recommender/top_books.csv
      top_genre_root: artifacts/model_trainer/simple_recommender/top_genre_books
    content_based:
      root_dir: artifacts/model_trainer/content_based_recommender
      model_path: artifacts/model_trainer/content_based_recommender/sim_matrix.joblib



# model_evaluation:
#   root_dir: artifacts/model_evaluation
#   test_data_path: artifacts/data_transformation/test.csv
#   model_path: artifacts/model_trainer/model.joblib
#   metric_file_name: artifacts/model_evaluation/metrics.json


model_prediction:
  simple:
    top_books: artifacts/model_trainer/simple_recommender/top_books.csv
    top_genre_root: artifacts/model_trainer/simple_recommender/top_genre_books
  content_based:
    books: artifacts/data_transformation/clean_books.csv
    model_path: artifacts/model_trainer/content_based_recommender/sim_matrix.joblib
    trusted_user:  artifacts/data_transformation/trusted_user.csv

